services:
  backend:
    build:
      context: .
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - backnet

  proxy:
    build: proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backnet

networks:
  backnet: