name: deploy

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: (Release) Get current date
        id: date
        run: echo "DATE=$(date + '%Y/%m/%d')" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: |
          ./gradlew -version
          ./gradlew clean build -x test
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name : Build Docker Image & Push to Docker Hub
        run: |
          docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-tutorial-18th:$DATE
          docker build ./proxy -t ${{ secrets.DOCKER_HUB_USERNAME }}/nginx
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-tutorial-18th:$DATE
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nginx